### ISSUE TITLE
ForIntExpression does not contain the iterator variable identifier

### ISSUE THREAD

**Issue by wayrick** [avast/yaramod#103]
example rule:
```yara
rule for_int_expression {
condition:
    for any i in (0 .. 100) : ( uint8(i) == uint8(i+10) )
}
```

produces:
```
==== RULE: for_int_expression
ForInt[0x7fc79339f618] 
    Any[0x7fc79339f650] 
    Range[0x7fc79339f650] 
        IntLiteral[0x7fc79339f6c0]  value=0
        IntLiteral[0x7fc79339f6c0]  value=100
    Eq[0x7fc79339f650] 
        IntFunction[0x7fc79339f6c0]  function=uint8
            Id[0x7fc79339f730]  id=i
        IntFunction[0x7fc79339f6c0]  function=uint8
            Plus[0x7fc79339f730] 
                Id[0x7fc79339f7a0]  id=i
                IntLiteral[0x7fc79339f7a0]  value=10
```

The identifier **i** does appear in (sub-expressions of) the **body** attribute of the expression but I would expect it should be in the **variable** attribute (since **any** and **all** are really just modifiers on how the **body** condition gets applied).

**Comment by metthal** [comment]
Thanks for bug report. So if I understand you correctly, you would expect to see `i` somewhere in between `Any` and `Range` right?

**Comment by wayrick** [comment]
> Thanks for bug report. So if I understand you correctly, you would expect to see `i` somewhere in between `Any` and `Range` right?

Yes, I would expect it to be in the **variable** attribute. The way I see it **any** / **all** / **expression before identifier** are modifiers of how the **body** expression gets applied. The way I see it **ForIntExpression** should have one of either:
 * **modifier** attribute for **any** / **all** / **numbers** / **expression** and have **variable** attribute for **i**
 * **variable** attribute should contain 2 attributes (e.g. **modifier** and **identifier**)

Also note that it should probably be variable*s* if also taking Yara 4.0 into account since one could write a module that returns tuples (i.e. iterating a dictionary).

Docs for Yara iterating over string occurrences [3.11.0](https://yara.readthedocs.io/en/v3.11.0/writingrules.html#iterating-over-string-occurrences) and [4.0.x iterators](https://yara.readthedocs.io/en/v4.0.1/writingrules.html#iterators)

This does seem to be a bit of an inconsistency in the Yara grammar itself because there is a **for of** expression that can't have an iterator (but uses the **$ # @** instead). The **for in** expression however use an iterator

**Comment by metthal** [comment]
> Yes, I would expect it to be in the variable attribute. The way I see it any / all / expression before identifier are modifiers of how the body expression gets applied. The way I see it ForIntExpression should have one of either:
> 
> * modifier attribute for any / all / numbers / expression and have variable attribute for i
> * variable attribute should contain 2 attributes (e.g. modifier and identifier)

Sure, we can do that and it makes sense. Thanks for noticing.

> Also note that it should probably be variables if also taking Yara 4.0 into account since one could write a module that returns tuples (i.e. iterating a dictionary).

We are currently still at 3.11 in yaramod but we're planning to integrate all 4.0 features soon. Can't promise when but we're planning it.
