### ISSUE TITLE
[Formatting] Segfault when formatting rules with `N of []` expression

### ISSUE THREAD

**Issue by MatejKastak** [avast/yaramod#161]
Yaramod can parse rules with this expression but cannot format them.

Repro:
```python
import yaramod

rule = r"""
import "time"

rule asd
{
    condition:
        1 of [ time.now(), time.now() ]
}
"""
ymod = yaramod.Yaramod()
a = ymod.parse_string(rule)

# Triggers the segfault
a.text_formatted
```
The actual called function `time.now()` does not matter, nor the number. I estimate that the problem is with brackets `[`.

I was able to trace the error here https://github.com/avast/yaramod/blob/master/src/types/token_stream.cpp#L423 , the `leftBrackets` is empty and calling `top()` returns an invalid element.

version: 0ad977e (current master)

**Comment by metthal** [comment]
Resolved in #170
