### ISSUE TITLE
Fix wrong Float representation and parsing

### ISSUE THREAD

**Issue by TadeasKucera** [avast/yaramod#177]
Float values are not parsed / stored correctly.

- Longer floats are trimmed: 0.869932552472 becomes 0.869933, which is undesirable.
- Many zeros behind the dot, like 0.0000000001 are stored as 1e-10 which is also not wanted.

I have added two tests into a new branch [fix_float_values](https://github.com/avast/yaramod/tree/fix_float_values) which demostrate the problem.

**Comment by metthal** [comment]
Resolved in #179
