### ISSUE TITLE
Add option to specify which style to use for curly braces placement

### ISSUE THREAD

**Issue by metthal** [avast/yaramod#34]
Currently, generated curly braces out of `yaramod` are always K&R or Egyptian braces, like this

```
rule abc {
    ...
}
```

It would be nice to be able to specify whether to use the already existing option or

```
rule abc
{
    ...
}
```

Once we implement #17, it will make sense to use this just for those rules which are generated from builder itself, not those which were parsed, but we might possibly override the behavior with this option.

**Comment by TadeasKucera** [comment]
The `getTextFormatted` function returns rules formatted as
```
rule abc
{
    ...
}
```
This feature is no longer needed.
