### ISSUE TITLE
Autoformatting of file with CRLF line endings and comments results in file with mixed line endings

### ISSUE THREAD

**Issue by metthal** [avast/yaramod#48]
If you take a file with CRLF line endings and put some comments in there, you end up with CR at the end of each comment while all other lines in the file have LF line endings. We should take care of it so that we end up with either only LF line endings (Linux + macOS) or CRLF line endings (Windows).

**Comment by metthal** [comment]
Regarding the last point that we should have LF on Linux + macOS and CRLF on Windows, this would break a lot of things when one person wants to autoformat from Linux machine and the other one from Windows machine. They would rewrite their line endings each time.

The way it works should be probably that when file has CRLF line endings, it autoformats with CRLF but when file has LF line endings, it should autoformat with LF. This will also work hand in hand with git `autocrlf` option which causes git on Windows to checkout files with CRLF but turns them to LF before they are checked in into commit.

**Comment by s3rvac** [comment]
Fixed in #49.
