### ISSUE TITLE
Add new import feature for deprecated functions

### ISSUE THREAD

**Issue by metthal** [avast/yaramod#62]
There are certain functions which were (or will be) deprecated in the YARA. We don't want them to be recognized by the default Yaramod but since we have import features, we can solve it using those.

I would propose adding new import feature `Deprecated` which would also add function that were deprecated (currently only `cuckoo.signature.name`). If this flag is not specified that deprecated functions won't be included in symbols.

**Comment by TadeasKucera** [comment]
That is a nice solution of the problem, I will implement it tomorrow. Thank you for the suggestion!
