### ISSUE TITLE
Modifying rule with ModifyingVisitor should also modify it when obtaining getTextFormatted()

### ISSUE THREAD

**Issue by metthal** [avast/yaramod#75]
This ticket is kinda related to #73 but it should also have its own because in some specific things it is a bit different.

Basically, we provide an option to modify the condition through `ModifyingVisitor` but these changes are not reflect when getting back the `text_formatted` out of `YaraFile`. This is caused by not directly modifying token streams when we are modifying the condition. For example following code:

```python
import json
import yaramod

class RegexpCaseInsesitiveAdder(yaramod.ModifyingVisitor):
    def add(self, yara_file: yaramod.YaraFile):
        for rule in yara_file.rules:
            new_condition = self.modify(rule.condition)
            print(new_condition.text)
            rule.condition = new_condition

    def visit_RegexpExpression(self, expr: yaramod.Expression):
        return yaramod.regexp('abc', 'i').get()

ymod = yaramod.Yaramod()
yfile = ymod.parse_file('/tmp/ruleset.yar')

regexp_icase_adder = RegexpCaseInsesitiveAdder()
regexp_icase_adder.add(yfile)

print(yfile.text_formatted)
```

This just replaces all regexes in conditions with `/abc/i` but when obtained through `text_formatted` it still return the original condition while it should return the modified one. It is expected that it returns the modified one.

**Comment by TadeasKucera** [comment]
This issue was solved with the introduction of _ModifyingVisitor::cleanup_tokenstreams_ which allows us to write ModifyingVisitors that also alter the formatted text of affected rules.
